import { ReactNode } from "react";
import type { ComponentPropsWithoutRef } from "react";

interface AlertProps extends ComponentPropsWithoutRef<"div"> {
  type?: string;
  children?: ReactNode;
}
function Alert({ type, children, ...props }: AlertProps) {
  const image =
    type === "success"
      ? "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAElBMVEUAAAAAAAAAgACAgID////AwMAbJqpVAAAAAXRSTlMAQObYZgAAAAFiS0dEBI9o2VEAAAAHdElNRQfiBhoANRyRjMyLAAAArElEQVQoz22R0Q3EIAiGNbfAeU4gad+9sMGFLtC4/yyngBaa+tCELz+fFkJ4PimltyljAoCSrvoDfBbRGkC74qyh3AIauQIacaCajo1+ANmARqcHRP2T61LsdIgkWoUFrICCC7Bigo1OUUzQK1GslkaiGIDfsZMoICvokcODXRTjpXpvU0W9/T5WP7GhcDNF9EPN3GH2ooEQvrI51EAIL+y7zbgCg/Cx68eZ/wNuLjeFQzbY1AAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAxOC0wNi0yNlQwMDo1MzoyOC0wNDowMGvaoe4AAAAldEVYdGRhdGU6bW9kaWZ5ADIwMTgtMDYtMjZUMDA6NTM6MjgtMDQ6MDAahxlSAAAAAElFTkSuQmCC"
      : type === "warning"
      ? "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAFVBMVEUAAACAgAD//wDAwMAAAACAgID////uPuK0AAAAAXRSTlMAQObYZgAAAAFiS0dEBmFmuH0AAAAHdElNRQfiBhoAKi/jBqMDAAAApUlEQVQoz12PwRHDIAwE4ZECwriBCCrIUEDiyH9/6L+VcMIgyfdjZ27FhSCJz+CT8se9I1E9b6A01yDKx+kBWdAbXdJuwErQcJJEld9G0hvMu5FcQCVpAJVcYElwVMCUAGwAU4Jf4OySABSmNUf+/frqHAH5p3NkCO06Z4ARAGlQxpUhGaDwPiXJAkiSrdACy9o8yB1EC2rr1o01B0BoNvjqw4LwB7hqPlTe+r15AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDE4LTA2LTI2VDAwOjQyOjQ3LTA0OjAwdbFsfgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAxOC0wNi0yNlQwMDo0Mjo0Ny0wNDowMATs1MIAAAAASUVORK5CYII="
      : type === "error"
      ? "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAD1BMVEUAAACAAAD/AACAgID///8kN7BFAAAAAXRSTlMAQObYZgAAAAFiS0dEBI9o2VEAAAAHdElNRQfiBhoAKi0NCMIvAAAApElEQVQoz3WR2xHEIAhFcdLAGiuQSQFm6GDH/mtaXj5CZvmC472IAiCRcs4fWJFPRKx51gkthiadDqqTUTN5GKZpB8Udl1Zf9jQTdM7x6uZJkkreBRdXcG60NL1UChVIE52iS+AGWKICrORzuuA/eFlWU4rXUhyM4ugUHsejP59PLXzQG4RPFsG+hmIA7mkgW8zhqyQXMLl52WXVAGSx7f+gcf4DIC49kP+gREgAAAAldEVYdGRhdGU6Y3JlYXRlADIwMTgtMDYtMjZUMDA6NDI6NDUtMDQ6MDDiLn1XAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDE4LTA2LTI2VDAwOjQyOjQ1LTA0OjAwk3PF6wAAAABJRU5ErkJggg=="
      : "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAFVBMVEUAAACAgADAwMD//////wAAAACAgIDI2DU5AAAAAXRSTlMAQObYZgAAAAFiS0dEAxEMTPIAAAAHdElNRQfiBhgXChft4EJBAAAAm0lEQVQoz53PPRICIQwF4FBobUQOANyA3QusE/sUcgPvfwaXv4WgY+Erv3lJACBH4R7oUdeweNdFae99CO7SQC8pztlWWClll1rRVOLqllogujsjgawRE0TYAaOEDfkpwcBLAhfgBg/IUApgYuR8e+Phv7oXjsd9FHCE2wR54g/4eVXFmJ47CqIdR9LXcIQzTUu/A087xE44HVffO00yLE/01uYAAAAldEVYdGRhdGU6Y3JlYXRlADIwMTgtMDYtMjRUMjM6MTA6MjMtMDQ6MDDpN7CVAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDE4LTA2LTI0VDIzOjEwOjIzLTA0OjAwmGoIKQAAAABJRU5ErkJggg==";
  return (
    <div
      className="m-2 bg-[#AAA8AB] p-3 text-xl rounded-sm flex items-center gap-4"
      {...props}>
      <img src={image} />
      {children}
    </div>
  );
}

export default Alert;
